"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def fibonacci(x : int):
    if x == 0 or x == 1:
        return x
    else:
        return fibonacci(x-1) + fibonacci(x-2)
    
i = 0
sum = 0
val = 0

while val <= 4000000:
    val = fibonacci(i)
    if val%2 == 0:
        sum += val
    i+=1

print(sum)
